server:
  port: 8080

spring:
  application:
    name: catalog-service

  data:
    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://mongo_user:1234@localhost:27017/catalog?authSource=admin
      database: catalog
