apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: chill
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: mshereef/order-service:1.0
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: order-service-config
            - secretRef:
                name: order-service-secret

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: chill
spec:
  selector:
    app: order-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
