# 1) Secret for postgres_order_db credentials
apiVersion: v1
kind: Secret
metadata:
  name: postgres-order-db-secret
  namespace: chill
type: Opaque
stringData:
  POSTGRES_DB:       "mydb"             # from your Compose file :contentReference[oaicite:0]{index=0}:contentReference[oaicite:1]{index=1}
  POSTGRES_USER:     "postgres_user"
  POSTGRES_PASSWORD: "1234"
