services:
  mongo_feedback_db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
    networks:
      - chill-network

  eureka-server:
    build: ./service_discovery
    container_name: eureka-server
    hostname: eureka-server
    ports:
      - "8761:8761"
    restart: always
    networks:
      - chill-network

  api-gateway-service:
    build: ./api_gateway
    container_name: api-gateway-service
    hostname: api-gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - chill-network

  feedback-service:
    build: ./feedback
    container_name: feedback-service
    hostname: feedback-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://mongo_user:1234@mongo_feedback_db:27017/mydb?authSource=admin"
    depends_on:
      - mongo_feedback_db
      - api-gateway-service
      - eureka-server
    networks:
      - chill-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://mongo_user:1234@mongo_catalog_db:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo_feedback_db
    networks:
      - chill-network

networks:
  chill-network:
    driver: bridge
