services:

  postgres_user_db:
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    networks:
      - chill-network

  user_service:
    build: ./user
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_user_db:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgres_user
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - postgres_user_db
    networks:
      - chill-network

  postgres_order_db:
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    networks:
      - chill-network

  order_service:
    build: ./order
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_order_db:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgres_user
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - postgres_order_db
    networks:
      - chill-network

  mongo_catalog_db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
    networks:
      - chill-network

  catalog_service:
    build: ./catalog
    ports:
      - "8082:8080"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://mongo_user:1234@mongo_catalog_db:27017/mydb?authSource=admin"
    depends_on:
      - mongo_catalog_db
    networks:
      - chill-network

  mongo_feedback_db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27018:27017"
    networks:
      - chill-network

  feedback_service:
    build: ./feedback
    ports:
      - "8083:8080"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://mongo_user:1234@mongo_feedback_db:27017/mydb?authSource=admin"
    depends_on:
      - mongo_feedback_db
    networks:
      - chill-network

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # RabbitMQ protocol (AMQP)
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - chill-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "9000:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://mongo_user:1234@mongo_catalog_db:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo_catalog_db
    networks:
      - chill-network

  pgadmin:
    image: dpage/pgadmin4  # pgAdmin official image
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "5050:80"  # Expose pgAdmin on localhost:5050
    networks:
      - chill-network

networks:
  chill-network:
    driver: bridge
