services:
  api-gateway-service:
    container_name: api-gateway-service
    hostname: api-gateway-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - chill-network

networks:
  chill-network:
    driver: bridge
