apiVersion: v1
kind: Service
metadata:
  name: feedback-service
  namespace: chill
spec:
  selector:
    app: feedback-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-service
  namespace: chill
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback-service
  template:
    metadata:
      labels:
        app: feedback-service
    spec:
      containers:
        - name: feedback-service
          image: mshereef/feedback-service:1.0
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: feedback-service-config


