scrape_configs:
  - job_name: 'feedback-service'
    # Spring Boot Actuator exposes Prometheus metrics here:
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['feedback-service:8082']
        labels:
          application: 'feedback-service'