server:
  port: 8082

spring:
  application:
    name: Feedback Microservice

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/feedbackdb}


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


