server:
  port: 8082

spring:
  application:
    name: feedback-service

  data:
    mongodb:
      host: localhost
      port: 27017
#      uri: ${SPRING_DATA_MONGODB_URI:mongo://localhost:27017/feedbackdb}
      uri: mongodb://root:example@localhost:27017/feedbackdb?authSource=admin
      database: feedbackdb

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enable: true
  show-actuator: true
  packages-to-scan: com.chill.feedback.controllers