SPRING_DATA_MONGODB_URI: mongodb://mongo_user:1234@localhost:27017/mydb?authSource=admin

server:
  port: 8083

spring:
  application:
    name: feedback-service

  data:
    mongodb:
      host: localhost
      port: 27017
      uri:  "mongodb://mongo_user:1234@mongo_feedback_db:27017/mydb?authSource=admin"
      database: feedbackdb

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    prometheus:
      enabled: true

sprgingdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enable: true
  show-actuator: true
  packages-to-scan: com.chill.feedback.controllers