apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: chill
spec:
  type: ClusterIP
  selector:
    app: api-gateway-service
  ports:
    - port: 9091
      targetPort: 9091

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
  namespace: chill
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
        - name: api-gateway
          image: mshereef/api-gateway:2.0
          ports:
            - containerPort: 9091
          envFrom:
            - configMapRef:
                name: api-gateway-config



