apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: chill
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-user-db:5432/mydb"
  SPRING_RABBITMQ_HOST: "rabbitmq"
---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: chill
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "postgres_user"
  SPRING_DATASOURCE_PASSWORD: "1234"