global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "user-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["user-service:8080"]
        labels:
          application: "user-service"

  - job_name: "order-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["order-service:8081"]
        labels:
          application: "order-service"

  - job_name: "catalog-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["catalog-service:8082"]
        labels:
          application: "catalog-service"

  - job_name: "feedback-service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["feedback-service:8083"]
        labels:
          application: "feedback-service"
