apiVersion: v1
kind: Service
metadata:
  name: mongo-catalog-db
  namespace: chill
  labels:
    app: mongo-catalog-db
spec:
  clusterIP: None                   # headless → per-Pod DNS
  selector:
    app: mongo-catalog-db           # matches StatefulSet pods
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017

---
# 3) StatefulSet for mongo-catalog-db with PVC-backed storage
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-catalog-db
  namespace: chill
spec:
  serviceName: mongo-catalog-db     # must match Service.metadata.name
  replicas: 1
  selector:
    matchLabels:
      app: mongo-catalog-db         # must equal template.metadata.labels
  template:
    metadata:
      labels:
        app: mongo-catalog-db       # picked up by the Service selector
    spec:
      containers:
        - name: mongo
          image: mongo:5.0
          ports:
            - name: mongodb
              containerPort: 27017
          envFrom:
            - secretRef:
                name: mongo-catalog-db-secret  # loads credentials
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data               # used by volumeMounts.name
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi